### PR TITLE
Remove _mm256_zeroupper() calls

### LINKED ISSUE #382: 61 - qa_volk_32f_x2_dot_prod_32f (Failed)
```
ctest -j 12 --test-load 12
Test project /var/tmp/portage/sci-libs/volk-2.3.0/work/volk-2.3.0_build
        Start   1: qa_volk_16i_32fc_dot_prod_32fc
        Start   2: qa_volk_16i_branch_4_state_8
        Start   3: qa_volk_16i_convert_8i
        Start   4: qa_volk_16i_max_star_16i
        Start   5: qa_volk_16i_max_star_horizontal_16i
        Start   6: qa_volk_16i_permute_and_scalar_add
        Start   7: qa_volk_16i_s32f_convert_32f
  1/134 Test   #2: qa_volk_16i_branch_4_state_8 .........................   Passed    0.01 sec
        Start   8: qa_volk_16i_x4_quad_max_star_16i
        Start   9: qa_volk_16i_x5_add_quad_16i_x4
        Start  10: qa_volk_16ic_convert_32fc
        Start  11: qa_volk_16ic_deinterleave_16i_x2
        Start  12: qa_volk_16ic_deinterleave_real_16i
        Start  13: qa_volk_16ic_deinterleave_real_8i
  2/134 Test   #3: qa_volk_16i_convert_8i ...............................   Passed    0.03 sec
        Start  14: qa_volk_16ic_magnitude_16i
  3/134 Test   #4: qa_volk_16i_max_star_16i .............................   Passed    0.03 sec
        Start  15: qa_volk_16ic_s32f_deinterleave_32f_x2
  4/134 Test   #5: qa_volk_16i_max_star_horizontal_16i ..................   Passed    0.04 sec
        Start  16: qa_volk_16ic_s32f_deinterleave_real_32f
  5/134 Test   #6: qa_volk_16i_permute_and_scalar_add ...................   Passed    0.04 sec
        Start  17: qa_volk_16ic_s32f_magnitude_32f
  6/134 Test   #8: qa_volk_16i_x4_quad_max_star_16i .....................   Passed    0.04 sec
        Start  18: qa_volk_16ic_x2_dot_prod_16ic
  7/134 Test   #9: qa_volk_16i_x5_add_quad_16i_x4 .......................   Passed    0.05 sec
        Start  19: qa_volk_16ic_x2_multiply_16ic
  8/134 Test   #1: qa_volk_16i_32fc_dot_prod_32fc .......................   Passed    0.07 sec
        Start  20: qa_volk_16u_byteswap
  9/134 Test   #7: qa_volk_16i_s32f_convert_32f .........................   Passed    0.06 sec
        Start  21: qa_volk_16u_byteswappuppet_16u
 10/134 Test  #11: qa_volk_16ic_deinterleave_16i_x2 .....................   Passed    0.04 sec
        Start  22: qa_volk_32f_64f_add_64f
 11/134 Test  #12: qa_volk_16ic_deinterleave_real_16i ...................   Passed    0.04 sec
        Start  23: qa_volk_32f_64f_multiply_64f
 12/134 Test  #13: qa_volk_16ic_deinterleave_real_8i ....................   Passed    0.04 sec
        Start  24: qa_volk_32f_8u_polarbutterfly_32f
 13/134 Test  #10: qa_volk_16ic_convert_32fc ............................   Passed    0.07 sec
        Start  25: qa_volk_32f_8u_polarbutterflypuppet_32f
 14/134 Test  #14: qa_volk_16ic_magnitude_16i ...........................   Passed    0.05 sec
        Start  26: qa_volk_32f_accumulator_s32f
 15/134 Test  #15: qa_volk_16ic_s32f_deinterleave_32f_x2 ................   Passed    0.05 sec
        Start  27: qa_volk_32f_acos_32f
 16/134 Test  #16: qa_volk_16ic_s32f_deinterleave_real_32f ..............   Passed    0.05 sec
        Start  28: qa_volk_32f_asin_32f
 17/134 Test  #20: qa_volk_16u_byteswap .................................   Passed    0.02 sec
        Start  29: qa_volk_32f_atan_32f
 18/134 Test  #17: qa_volk_16ic_s32f_magnitude_32f ......................   Passed    0.06 sec
        Start  30: qa_volk_32f_binary_slicer_32i
 19/134 Test  #18: qa_volk_16ic_x2_dot_prod_16ic ........................   Passed    0.06 sec
        Start  31: qa_volk_32f_binary_slicer_8i
 20/134 Test  #19: qa_volk_16ic_x2_multiply_16ic ........................   Passed    0.06 sec
        Start  32: qa_volk_32f_convert_64f
 21/134 Test  #21: qa_volk_16u_byteswappuppet_16u .......................   Passed    0.05 sec
        Start  33: qa_volk_32f_cos_32f
 22/134 Test  #24: qa_volk_32f_8u_polarbutterfly_32f ....................   Passed    0.04 sec
        Start  34: qa_volk_32f_exp_32f
 23/134 Test  #22: qa_volk_32f_64f_add_64f ..............................   Passed    0.06 sec
        Start  35: qa_volk_32f_expfast_32f
 24/134 Test  #23: qa_volk_32f_64f_multiply_64f .........................   Passed    0.05 sec
        Start  36: qa_volk_32f_index_max_16u
 25/134 Test  #26: qa_volk_32f_accumulator_s32f .........................   Passed    0.05 sec
        Start  37: qa_volk_32f_index_max_32u
 26/134 Test  #27: qa_volk_32f_acos_32f .................................   Passed    0.06 sec
        Start  38: qa_volk_32f_invsqrt_32f
 27/134 Test  #28: qa_volk_32f_asin_32f .................................   Passed    0.05 sec
        Start  39: qa_volk_32f_log2_32f
 28/134 Test  #29: qa_volk_32f_atan_32f .................................   Passed    0.05 sec
        Start  40: qa_volk_32f_null_32f
 29/134 Test  #30: qa_volk_32f_binary_slicer_32i ........................   Passed    0.04 sec
        Start  41: qa_volk_32f_s32f_32f_fm_detect_32f
 30/134 Test  #31: qa_volk_32f_binary_slicer_8i .........................   Passed    0.04 sec
        Start  42: qa_volk_32f_s32f_add_32f
 31/134 Test  #34: qa_volk_32f_exp_32f ..................................   Passed    0.02 sec
        Start  43: qa_volk_32f_s32f_calc_spectral_noise_floor_32f
 32/134 Test  #25: qa_volk_32f_8u_polarbutterflypuppet_32f ..............   Passed    0.09 sec
        Start  44: qa_volk_32f_s32f_convert_16i
 33/134 Test  #32: qa_volk_32f_convert_64f ..............................   Passed    0.07 sec
        Start  45: qa_volk_32f_s32f_convert_32i
 34/134 Test  #33: qa_volk_32f_cos_32f ..................................   Passed    0.07 sec
        Start  46: qa_volk_32f_s32f_convert_8i
 35/134 Test  #35: qa_volk_32f_expfast_32f ..............................   Passed    0.05 sec
        Start  47: qa_volk_32f_s32f_mod_rangepuppet_32f
 36/134 Test  #36: qa_volk_32f_index_max_16u ............................   Passed    0.05 sec
        Start  48: qa_volk_32f_s32f_multiply_32f
 37/134 Test  #38: qa_volk_32f_invsqrt_32f ..............................   Passed    0.05 sec
        Start  49: qa_volk_32f_s32f_normalize
 38/134 Test  #37: qa_volk_32f_index_max_32u ............................   Passed    0.06 sec
        Start  50: qa_volk_32f_s32f_power_32f
 39/134 Test  #39: qa_volk_32f_log2_32f .................................   Passed    0.05 sec
        Start  51: qa_volk_32f_s32f_s32f_mod_range_32f
 40/134 Test  #40: qa_volk_32f_null_32f .................................   Passed    0.04 sec
        Start  52: qa_volk_32f_s32f_stddev_32f
 41/134 Test  #41: qa_volk_32f_s32f_32f_fm_detect_32f ...................   Passed    0.04 sec
        Start  53: qa_volk_32f_sin_32f
 42/134 Test  #42: qa_volk_32f_s32f_add_32f .............................   Passed    0.04 sec
        Start  54: qa_volk_32f_sqrt_32f
 43/134 Test  #43: qa_volk_32f_s32f_calc_spectral_noise_floor_32f .......   Passed    0.03 sec
        Start  55: qa_volk_32f_stddev_and_mean_32f_x2
 44/134 Test  #44: qa_volk_32f_s32f_convert_16i .........................   Passed    0.06 sec
        Start  56: qa_volk_32f_tan_32f
 45/134 Test  #45: qa_volk_32f_s32f_convert_32i .........................   Passed    0.05 sec
        Start  57: qa_volk_32f_tanh_32f
 46/134 Test  #46: qa_volk_32f_s32f_convert_8i ..........................   Passed    0.05 sec
        Start  58: qa_volk_32f_x2_add_32f
 47/134 Test  #47: qa_volk_32f_s32f_mod_rangepuppet_32f .................   Passed    0.05 sec
        Start  59: qa_volk_32f_x2_divide_32f
 48/134 Test  #48: qa_volk_32f_s32f_multiply_32f ........................   Passed    0.04 sec
        Start  60: qa_volk_32f_x2_dot_prod_16i
 49/134 Test  #49: qa_volk_32f_s32f_normalize ...........................   Passed    0.04 sec
        Start  61: qa_volk_32f_x2_dot_prod_32f
 50/134 Test  #51: qa_volk_32f_s32f_s32f_mod_range_32f ..................   Passed    0.03 sec
        Start  62: qa_volk_32f_x2_fm_detectpuppet_32f
 51/134 Test  #50: qa_volk_32f_s32f_power_32f ...........................   Passed    0.07 sec
        Start  63: qa_volk_32f_x2_interleave_32fc
 52/134 Test  #52: qa_volk_32f_s32f_stddev_32f ..........................   Passed    0.06 sec
        Start  64: qa_volk_32f_x2_max_32f
 53/134 Test  #53: qa_volk_32f_sin_32f ..................................   Passed    0.06 sec
        Start  65: qa_volk_32f_x2_min_32f
 54/134 Test  #54: qa_volk_32f_sqrt_32f .................................   Passed    0.06 sec
        Start  66: qa_volk_32f_x2_multiply_32f
 55/134 Test  #55: qa_volk_32f_stddev_and_mean_32f_x2 ...................   Passed    0.06 sec
        Start  67: qa_volk_32f_x2_pow_32f
 56/134 Test  #56: qa_volk_32f_tan_32f ..................................   Passed    0.07 sec
        Start  68: qa_volk_32f_x2_s32f_interleave_16ic
 57/134 Test  #57: qa_volk_32f_tanh_32f .................................   Passed    0.07 sec
        Start  69: qa_volk_32f_x2_subtract_32f
 58/134 Test  #58: qa_volk_32f_x2_add_32f ...............................   Passed    0.06 sec
        Start  70: qa_volk_32f_x3_sum_of_poly_32f
 59/134 Test  #59: qa_volk_32f_x2_divide_32f ............................   Passed    0.06 sec
        Start  71: qa_volk_32fc_32f_add_32fc
 60/134 Test  #60: qa_volk_32f_x2_dot_prod_16i ..........................   Passed    0.07 sec
        Start  72: qa_volk_32fc_32f_dot_prod_32fc
 61/134 Test  #62: qa_volk_32f_x2_fm_detectpuppet_32f ...................   Passed    0.06 sec
        Start  73: qa_volk_32fc_32f_multiply_32fc
 62/134 Test  #63: qa_volk_32f_x2_interleave_32fc .......................   Passed    0.06 sec
        Start  74: qa_volk_32fc_conjugate_32fc
 63/134 Test  #61: qa_volk_32f_x2_dot_prod_32f ..........................***Failed    0.09 sec
        Start  75: qa_volk_32fc_convert_16ic
 64/134 Test  #64: qa_volk_32f_x2_max_32f ...............................   Passed    0.08 sec
        Start  76: qa_volk_32fc_deinterleave_32f_x2
 65/134 Test  #65: qa_volk_32f_x2_min_32f ...............................   Passed    0.08 sec
        Start  77: qa_volk_32fc_deinterleave_64f_x2
 66/134 Test  #66: qa_volk_32f_x2_multiply_32f ..........................   Passed    0.08 sec
        Start  78: qa_volk_32fc_deinterleave_imag_32f
 67/134 Test  #69: qa_volk_32f_x2_subtract_32f ..........................   Passed    0.06 sec
        Start  79: qa_volk_32fc_deinterleave_real_32f
 68/134 Test  #67: qa_volk_32f_x2_pow_32f ...............................   Passed    0.08 sec
        Start  80: qa_volk_32fc_deinterleave_real_64f
 69/134 Test  #68: qa_volk_32f_x2_s32f_interleave_16ic ..................   Passed    0.07 sec
        Start  81: qa_volk_32fc_index_max_16u
 70/134 Test  #70: qa_volk_32f_x3_sum_of_poly_32f .......................   Passed    0.08 sec
        Start  82: qa_volk_32fc_index_max_32u
 71/134 Test  #71: qa_volk_32fc_32f_add_32fc ............................   Passed    0.07 sec
        Start  83: qa_volk_32fc_magnitude_32f
 72/134 Test  #73: qa_volk_32fc_32f_multiply_32fc .......................   Passed    0.08 sec
        Start  84: qa_volk_32fc_magnitude_squared_32f
 73/134 Test  #75: qa_volk_32fc_convert_16ic ............................   Passed    0.07 sec
        Start  85: qa_volk_32fc_s32f_atan2_32f
 74/134 Test  #76: qa_volk_32fc_deinterleave_32f_x2 .....................   Passed    0.07 sec
        Start  86: qa_volk_32fc_s32f_deinterleave_real_16i
 75/134 Test  #79: qa_volk_32fc_deinterleave_real_32f ...................   Passed    0.06 sec
        Start  87: qa_volk_32fc_s32f_magnitude_16i
 76/134 Test  #74: qa_volk_32fc_conjugate_32fc ..........................   Passed    0.09 sec
        Start  88: qa_volk_32fc_s32f_power_32fc
 77/134 Test  #72: qa_volk_32fc_32f_dot_prod_32fc .......................   Passed    0.10 sec
        Start  89: qa_volk_32fc_s32f_power_spectral_densitypuppet_32f
 78/134 Test  #78: qa_volk_32fc_deinterleave_imag_32f ...................   Passed    0.07 sec
        Start  90: qa_volk_32fc_s32f_power_spectrum_32f
 79/134 Test  #80: qa_volk_32fc_deinterleave_real_64f ...................   Passed    0.07 sec
        Start  91: qa_volk_32fc_s32f_x2_power_spectral_density_32f
 80/134 Test  #81: qa_volk_32fc_index_max_16u ...........................   Passed    0.06 sec
        Start  92: qa_volk_32fc_s32fc_multiply_32fc
 81/134 Test  #77: qa_volk_32fc_deinterleave_64f_x2 .....................   Passed    0.09 sec
        Start  93: qa_volk_32fc_s32fc_rotatorpuppet_32fc
 82/134 Test  #82: qa_volk_32fc_index_max_32u ...........................   Passed    0.05 sec
        Start  94: qa_volk_32fc_s32fc_x2_rotator_32fc
 83/134 Test  #85: qa_volk_32fc_s32f_atan2_32f ..........................   Passed    0.06 sec
        Start  95: qa_volk_32fc_x2_add_32fc
 84/134 Test  #86: qa_volk_32fc_s32f_deinterleave_real_16i ..............   Passed    0.06 sec
        Start  96: qa_volk_32fc_x2_conjugate_dot_prod_32fc
 85/134 Test  #87: qa_volk_32fc_s32f_magnitude_16i ......................   Passed    0.06 sec
        Start  97: qa_volk_32fc_x2_divide_32fc
 86/134 Test  #91: qa_volk_32fc_s32f_x2_power_spectral_density_32f ......   Passed    0.04 sec
        Start  98: qa_volk_32fc_x2_dot_prod_32fc
 87/134 Test  #83: qa_volk_32fc_magnitude_32f ...........................   Passed    0.09 sec
        Start  99: qa_volk_32fc_x2_multiply_32fc
 88/134 Test  #88: qa_volk_32fc_s32f_power_32fc .........................   Passed    0.06 sec
        Start 100: qa_volk_32fc_x2_multiply_conjugate_32fc
 89/134 Test  #89: qa_volk_32fc_s32f_power_spectral_densitypuppet_32f ...   Passed    0.05 sec
        Start 101: qa_volk_32fc_x2_s32f_square_dist_scalar_mult_32f
 90/134 Test  #90: qa_volk_32fc_s32f_power_spectrum_32f .................   Passed    0.05 sec
        Start 102: qa_volk_32fc_x2_s32fc_multiply_conjugate_add_32fc
 91/134 Test  #84: qa_volk_32fc_magnitude_squared_32f ...................   Passed    0.08 sec
        Start 103: qa_volk_32fc_x2_square_dist_32f
 92/134 Test  #94: qa_volk_32fc_s32fc_x2_rotator_32fc ...................   Passed    0.02 sec
        Start 104: qa_volk_32i_s32f_convert_32f
 93/134 Test  #92: qa_volk_32fc_s32fc_multiply_32fc .....................   Passed    0.10 sec
        Start 105: qa_volk_32i_x2_and_32i
 94/134 Test  #93: qa_volk_32fc_s32fc_rotatorpuppet_32fc ................   Passed    0.09 sec
        Start 106: qa_volk_32i_x2_or_32i
 95/134 Test  #95: qa_volk_32fc_x2_add_32fc .............................   Passed    0.09 sec
        Start 107: qa_volk_32u_byteswap
 96/134 Test  #97: qa_volk_32fc_x2_divide_32fc ..........................   Passed    0.09 sec
        Start 108: qa_volk_32u_byteswappuppet_32u
 97/134 Test  #96: qa_volk_32fc_x2_conjugate_dot_prod_32fc ..............   Passed    0.11 sec
        Start 109: qa_volk_32u_popcnt
 98/134 Test #104: qa_volk_32i_s32f_convert_32f .........................   Passed    0.06 sec
        Start 110: qa_volk_32u_popcntpuppet_32u
 99/134 Test #100: qa_volk_32fc_x2_multiply_conjugate_32fc ..............   Passed    0.11 sec
        Start 111: qa_volk_32u_reverse_32u
100/134 Test #103: qa_volk_32fc_x2_square_dist_32f ......................   Passed    0.08 sec
        Start 112: qa_volk_64f_convert_32f
101/134 Test #107: qa_volk_32u_byteswap .................................   Passed    0.03 sec
        Start 113: qa_volk_64f_x2_add_64f
102/134 Test #105: qa_volk_32i_x2_and_32i ...............................   Passed    0.07 sec
        Start 114: qa_volk_64f_x2_max_64f
103/134 Test #106: qa_volk_32i_x2_or_32i ................................   Passed    0.06 sec
        Start 115: qa_volk_64f_x2_min_64f
104/134 Test #108: qa_volk_32u_byteswappuppet_32u .......................   Passed    0.04 sec
        Start 116: qa_volk_64f_x2_multiply_64f
105/134 Test #109: qa_volk_32u_popcnt ...................................   Passed    0.03 sec
        Start 117: qa_volk_64u_byteswap
106/134 Test  #99: qa_volk_32fc_x2_multiply_32fc ........................   Passed    0.13 sec
        Start 118: qa_volk_64u_byteswappuppet_64u
107/134 Test  #98: qa_volk_32fc_x2_dot_prod_32fc ........................   Passed    0.17 sec
        Start 119: qa_volk_64u_popcnt
108/134 Test #101: qa_volk_32fc_x2_s32f_square_dist_scalar_mult_32f .....   Passed    0.16 sec
        Start 120: qa_volk_64u_popcntpuppet_64u
109/134 Test #102: qa_volk_32fc_x2_s32fc_multiply_conjugate_add_32fc ....   Passed    0.16 sec
        Start 121: qa_volk_8i_convert_16i
110/134 Test #110: qa_volk_32u_popcntpuppet_32u .........................   Passed    0.08 sec
        Start 122: qa_volk_8i_s32f_convert_32f
111/134 Test #111: qa_volk_32u_reverse_32u ..............................   Passed    0.07 sec
        Start 123: qa_volk_8ic_deinterleave_16i_x2
112/134 Test #112: qa_volk_64f_convert_32f ..............................   Passed    0.07 sec
        Start 124: qa_volk_8ic_deinterleave_real_16i
113/134 Test #117: qa_volk_64u_byteswap .................................   Passed    0.04 sec
        Start 125: qa_volk_8ic_deinterleave_real_8i
114/134 Test #119: qa_volk_64u_popcnt ...................................   Passed    0.03 sec
        Start 126: qa_volk_8ic_s32f_deinterleave_32f_x2
115/134 Test #113: qa_volk_64f_x2_add_64f ...............................   Passed    0.09 sec
        Start 127: qa_volk_8ic_s32f_deinterleave_real_32f
116/134 Test #114: qa_volk_64f_x2_max_64f ...............................   Passed    0.08 sec
        Start 128: qa_volk_8ic_x2_multiply_conjugate_16ic
117/134 Test #115: qa_volk_64f_x2_min_64f ...............................   Passed    0.07 sec
        Start 129: qa_volk_8ic_x2_s32f_multiply_conjugate_32fc
118/134 Test #116: qa_volk_64f_x2_multiply_64f ..........................   Passed    0.09 sec
        Start 130: qa_volk_8u_conv_k7_r2puppet_8u
119/134 Test #118: qa_volk_64u_byteswappuppet_64u .......................   Passed    0.08 sec
        Start 131: qa_volk_8u_x2_encodeframepolar_8u
120/134 Test #120: qa_volk_64u_popcntpuppet_64u .........................   Passed    0.07 sec
        Start 132: qa_volk_8u_x3_encodepolar_8u_x2
121/134 Test #121: qa_volk_8i_convert_16i ...............................   Passed    0.06 sec
        Start 133: qa_volk_8u_x3_encodepolarpuppet_8u
122/134 Test #122: qa_volk_8i_s32f_convert_32f ..........................   Passed    0.06 sec
        Start 134: qa_volk_8u_x4_conv_k7_r2_8u
123/134 Test #123: qa_volk_8ic_deinterleave_16i_x2 ......................   Passed    0.06 sec
124/134 Test #124: qa_volk_8ic_deinterleave_real_16i ....................   Passed    0.05 sec
125/134 Test #125: qa_volk_8ic_deinterleave_real_8i .....................   Passed    0.05 sec
126/134 Test #127: qa_volk_8ic_s32f_deinterleave_real_32f ...............   Passed    0.04 sec
127/134 Test #126: qa_volk_8ic_s32f_deinterleave_32f_x2 .................   Passed    0.04 sec
128/134 Test #131: qa_volk_8u_x2_encodeframepolar_8u ....................   Passed    0.02 sec
129/134 Test #128: qa_volk_8ic_x2_multiply_conjugate_16ic ...............   Passed    0.03 sec
130/134 Test #132: qa_volk_8u_x3_encodepolar_8u_x2 ......................   Passed    0.02 sec
131/134 Test #134: qa_volk_8u_x4_conv_k7_r2_8u ..........................   Passed    0.01 sec
132/134 Test #129: qa_volk_8ic_x2_s32f_multiply_conjugate_32fc ..........   Passed    0.04 sec
133/134 Test #133: qa_volk_8u_x3_encodepolarpuppet_8u ...................   Passed    0.03 sec
134/134 Test #130: qa_volk_8u_conv_k7_r2puppet_8u .......................   Passed    0.05 sec

99% tests passed, 1 tests failed out of 134

Total Test time (real) =   0.80 sec

The following tests FAILED:
	 61 - qa_volk_32f_x2_dot_prod_32f (Failed)
Errors while running CTest
```

### LINKED ISSUE #384: 18 - qa_volk_16ic_x2_dot_prod_16ic (Failed)
Similar issue as #382. I'm guessing the solution will be similar.
Running the commands as per the other issue:
```
$ ctest -VV -R x2_dot_prod
UpdateCTestConfiguration  from :/home/jd/source/volk/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jd/source/volk/build/DartConfiguration.tcl
Test project /home/jd/source/volk/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 18
    Start 18: qa_volk_16ic_x2_dot_prod_16ic

18: Test command: /bin/sh "/home/jd/source/volk/build/lib/volk_16ic_x2_dot_prod_16ic_test.sh" "/home/jd/source/volk/build/lib"
18: Test timeout computed to be: 10000000
18: RUN_VOLK_TESTS: volk_16ic_x2_dot_prod_16ic(131071,1)
18: generic completed in 1.30312 ms
18: a_sse2 completed in 0.064963 ms
18: u_sse2 completed in 0.051387 ms
18: u_axv2 completed in 0.043813 ms
18: a_axv2 completed in 0.037481 ms
18: offset 0 in1: 3448 in2: -5774 tolerance was: 0
18: offset 1 in1: 2647 in2: -1393 tolerance was: 0
18: volk_16ic_x2_dot_prod_16ic: fail on arch u_axv2
18: offset 0 in1: 3448 in2: -5774 tolerance was: 0
18: offset 1 in1: 2647 in2: -1393 tolerance was: 0
18: volk_16ic_x2_dot_prod_16ic: fail on arch a_axv2
18: Best aligned arch: a_axv2
18: Best unaligned arch: u_axv2
1/4 Test #18: qa_volk_16ic_x2_dot_prod_16ic ....***Failed    0.01 sec
test 60
    Start 60: qa_volk_32f_x2_dot_prod_16i

60: Test command: /bin/sh "/home/jd/source/volk/build/lib/volk_32f_x2_dot_prod_16i_test.sh" "/home/jd/source/volk/build/lib"
60: Test timeout computed to be: 10000000
60: RUN_VOLK_TESTS: volk_32f_x2_dot_prod_16i(131071,1)
60: generic completed in 0.194837 ms
60: a_sse completed in 0.062517 ms
60: a_avx2_fma completed in 0.067287 ms
60: a_avx completed in 0.057749 ms
60: u_sse completed in 0.051096 ms
60: u_avx2_fma completed in 0.049273 ms
60: u_avx completed in 0.039614 ms
60: Best aligned arch: u_avx
60: Best unaligned arch: u_avx
2/4 Test #60: qa_volk_32f_x2_dot_prod_16i ......   Passed    0.01 sec
test 61
    Start 61: qa_volk_32f_x2_dot_prod_32f

61: Test command: /bin/sh "/home/jd/source/volk/build/lib/volk_32f_x2_dot_prod_32f_test.sh" "/home/jd/source/volk/build/lib"
61: Test timeout computed to be: 10000000
61: RUN_VOLK_TESTS: volk_32f_x2_dot_prod_32f(131071,1)
61: generic completed in 0.131317 ms
61: u_sse completed in 0.061446 ms
61: u_sse3 completed in 0.066034 ms
61: u_sse4_1 completed in 0.073869 ms
61: u_avx completed in 0.064982 ms
61: u_avx2_fma completed in 0.067697 ms
61: a_generic completed in 0.125186 ms
61: a_sse completed in 0.055875 ms
61: a_sse3 completed in 0.05333 ms
61: a_sse4_1 completed in 0.058911 ms
61: a_avx completed in 0.04748 ms
61: a_avx2_fma completed in 0.040386 ms
61: Best aligned arch: a_avx2_fma
61: Best unaligned arch: u_sse
3/4 Test #61: qa_volk_32f_x2_dot_prod_32f ......   Passed    0.02 sec
test 98
    Start 98: qa_volk_32fc_x2_dot_prod_32fc

98: Test command: /bin/sh "/home/jd/source/volk/build/lib/volk_32fc_x2_dot_prod_32fc_test.sh" "/home/jd/source/volk/build/lib"
98: Test timeout computed to be: 10000000
98: RUN_VOLK_TESTS: volk_32fc_x2_dot_prod_32fc(131071,1)
98: generic completed in 0.245924 ms
98: u_sse_64 completed in 0.145333 ms
98: u_sse3 completed in 0.136978 ms
98: u_sse4_1 completed in 0.180961 ms
98: u_avx completed in 0.130155 ms
98: u_avx_fma completed in 0.104727 ms
98: a_generic completed in 0.235944 ms
98: a_sse_64 completed in 0.091292 ms
98: a_sse3 completed in 0.09048 ms
98: a_sse4_1 completed in 0.162806 ms
98: a_avx completed in 0.091222 ms
98: a_avx_fma completed in 0.087926 ms
98: Best aligned arch: a_avx_fma
98: Best unaligned arch: u_avx_fma
4/4 Test #98: qa_volk_32fc_x2_dot_prod_32fc ....   Passed    0.04 sec

The following tests passed:
	qa_volk_32f_x2_dot_prod_16i
	qa_volk_32f_x2_dot_prod_32f
	qa_volk_32fc_x2_dot_prod_32fc

75% tests passed, 1 tests failed out of 4

Total Test time (real) =   0.09 sec

The following tests FAILED:
	 18 - qa_volk_16ic_x2_dot_prod_16ic (Failed)
Errors while running CTest
```

Here is my CPU (I have removed the other 15 entries as they are duplicates):
```
$ cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 8
model name	: AMD Ryzen 7 2700X Eight-Core Processor
stepping	: 2
microcode	: 0x800820d
cpu MHz		: 2068.633
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 7385.33
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```

As per the other issue, removing the two lines containing `_mm256_zeroupper` causes the tests to pass.

I'm using gcc-10 from `ppa:ubuntu-toolchain-r/test`:
```
$ gcc --version
gcc (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### PR DESCRIPTION
**Pull request by rear1019**
See commit message and discussion in #384 for details. TLDR: manual usage of `_mm256_zeroupper()` is not required and leads to miscompilation with GCC 10.2 and optimization level `-O3`.

This fixes #384.
This fixes #382.

### CODE REVIEW

File: kernels/volk/volk_32f_8u_polarbutterfly_32f.h [hunk 1]
```diff
@@ -246,7 +246,6 @@ static inline void volk_32f_8u_polarbutterfly_32f_u_avx(float* llrs,
         memcpy(u_temp, u + u_num - stage_size, sizeof(unsigned char) * stage_size);
 
         if (stage_size > 15) {
-            _mm256_zeroupper();
```
Comment (jdemel) [inline kernels/volk/volk_32f_8u_polarbutterfly_32f.h:249]: This would actually be a place where zeroupper makes sense. It is followed by a function that uses SSSE3 instructions.

File: kernels/volk/volk_32f_8u_polarbutterfly_32f.h [hunk 2]
```diff
@@ -259,7 +258,6 @@ static inline void volk_32f_8u_polarbutterfly_32f_u_avx(float* llrs,
 
         int p;
         for (p = 0; p < stage_size; p += 8) {
-            _mm256_zeroupper();
```
Comment (jdemel) [inline kernels/volk/volk_32f_8u_polarbutterfly_32f.h:262]: I wonder if this zeroupper call should stay here too. It is part of a loop where SSE and AVX instructions are interleaved.

File: kernels/volk/volk_32f_8u_polarbutterfly_32f.h [hunk 3]
```diff
@@ -347,7 +345,6 @@ static inline void volk_32f_8u_polarbutterfly_32f_u_avx2(float* llrs,
         memcpy(u_temp, u + u_num - stage_size, sizeof(unsigned char) * stage_size);
 
         if (stage_size > 15) {
-            _mm256_zeroupper();
```
Comment (jdemel) [inline kernels/volk/volk_32f_8u_polarbutterfly_32f.h:350]: See comment for line 249.

File: kernels/volk/volk_32f_8u_polarbutterfly_32f.h [hunk 4]
```diff
@@ -360,7 +357,6 @@ static inline void volk_32f_8u_polarbutterfly_32f_u_avx2(float* llrs,
 
         int p;
         for (p = 0; p < stage_size; p += 8) {
-            _mm256_zeroupper();
```
Comment (jdemel) [inline kernels/volk/volk_32f_8u_polarbutterfly_32f.h:363]: see comment for line 262.

**Review by jdemel — COMMENTED** [review]
Overall the PR looks good to me.
I would suggest to keep the zeroupper calls in `polarbutterfly` though. There, they are explicitly used to interleave SSE and AVX code.

**Comment by rear1019** [comment]
> Overall the PR looks good to me.
> I would suggest to keep the zeroupper calls in `polarbutterfly` though. There, they are explicitly used to interleave SSE and AVX code.

Removing the calls should be fine if my understanding of the mess regarding mixing AVX and SSE is correct. See the links mentioned in the commit message. Chapters “13.1 Using AVX instruction set and YMM or ZMM registers” and “13.2 Mixing VEX and SSE code” in [1] are a nice summary.

Mixing AVX and SSE instructions is fine as long as the SSE instruction use a new encoding scheme. As the code in question is compiled with `-mavx[2]` the compiler should do the right thing (see `-msse2avx` flag). `./apps/volk_profile -n -R polar -v 16384` does not show a performance regression on my Intel machine (AVX only).

[1] https://www.agner.org/optimize/optimizing_assembly.pdf

**Comment by jdemel** [comment]
I tested it on a Ryzen 4750 and could not find any performance regression as well. I'd say this is ready to be merged.

**Review by jdemel — APPROVED** [review]
LGTM

**Review by michaelld — APPROVED** [review]
I'm good with removing `_mm256_zeroupper` as done here. Worth a try IMHO!
