### PR TITLE
Fixups: Various Boost and include ordering

### LINKED ISSUE #234: Volk uses out-of-build headers of prior volk install if available
Steps to reproduce:

From Mac terminal (Late 2013 running 10.14.2):

I used revision dd5e293c85975d4db6718aef685b1a15de88a74f

```
git clone https://github.com/gnuradio/volk.git
cd volk/
mkdir build
cd build
cmake ..
make -j4
```

Compiler error is attached

[error.txt](https://github.com/gnuradio/volk/files/2800550/error.txt)

### PR DESCRIPTION
**Pull request by michaelld**
Closes: https://github.com/gnuradio/volk/issues/234

Remove Boost usage from `lib`, and fix it in `apps` to be used only if `std::filesystem` is not found.

Tweak include directories ordering slightly, and be more precise in specifying whether they are PUBLIC or PRIVATE, and add verbose notes as to why.

Some whilespace tweaks and removing unnecessary ""s too.

### CODE REVIEW

File: lib/qa_utils.h [hunk 1]
```diff
@@ -142,14 +142,6 @@ bool run_volk_tests(
...
 );
 
-
-#define VOLK_RUN_TESTS(func, tol, scalar, len, iter) \
-    BOOST_AUTO_TEST_CASE(func##_test) { \
-        BOOST_CHECK_EQUAL(run_volk_tests( \
-            func##_get_func_desc(), (void (*)())func##_manual, \
-            std::string(#func), tol, scalar, len, iter, 0, "NULL"), \
-          0); \
-    }
```
Comment (jdemel) [inline lib/qa_utils.h:152]: I'm happy that this part is removed. I stumbled over it multiple times.

**Review by jdemel — APPROVED** [review]
Tested this PR. Couldn't find any errors. I'm happy that things are more verbose now. LGTM.

**Comment by michaelld** [comment]
CI passes that we care about; failures are not due to this PR. Maintainer approves. Merging.
