### PR TITLE
Code cleanup

### LINKED ISSUE #327: Code cleanup
@michaelld https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/lib/qa_utils.cc#L624
The 'A = !fail' expression is equivalent to the 'A = false' expression. (We are in if (fail); )
https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/lib/qa_utils.cc#L144
Throw what?
https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/lib/volk_prefs.c#L81
No check for null. And consider assigning realloc() to a temporary pointer.

https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/tmpl/volk_cpu.tmpl.c#L114
Why it is equivalent to get_avx_enabled? Should not the check be different?

https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/apps/volk_profile.cc#L199-L201
Change that to `std::size_t found = config_str.find(' ');`

https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/apps/volk_profile.cc#L169
return 0;

```
./volk/kernels/volk/volk_32f_x2_pow_32f.h	348	note	V624 The constant 0.6931471805 is being utilized. The resulting value could be inaccurate. Consider using the M_LN2 constant from <math.h>.
./volk/kernels/volk/volk_32f_x2_pow_32f.h	496	note	V624 The constant 0.6931471805 is being utilized. The resulting value could be inaccurate. Consider using the M_LN2 constant from <math.h>.
./volk/kernels/volk/volk_32f_x2_pow_32f.h	111	note	V624 The constant 0.6931471805 is being utilized. The resulting value could be inaccurate. Consider using the M_LN2 constant from <math.h>.
./volk/kernels/volk/volk_32f_x2_pow_32f.h	229	note	V624 The constant 0.6931471805 is being utilized. The resulting value could be inaccurate. Consider using the M_LN2 constant from <math.h>.
./volk/kernels/volk/volk_32f_x2_pow_32f.h	614	note	V624 The constant 0.6931471805 is being utilized. The resulting value could be inaccurate. Consider using the M_LN2 constant from <math.h>.
./volk/kernels/volk/volk_32f_x2_pow_32f.h	733	note	V624 The constant 0.6931471805 is being utilized. The resulting value could be inaccurate. Consider using the M_LN2 constant from <math.h>.
./volk/kernels/volk/volk_8u_conv_k7_r2puppet_8u.h	304	err	V547 Expression 'd_polys[i] < 0' is always false.
./volk/kernels/volk/volk_8u_conv_k7_r2puppet_8u.h	151	err	V547 Expression 'd_polys[i] < 0' is always false.
./volk/kernels/volk/volk_8u_conv_k7_r2puppet_8u.h	227	err	V547 Expression 'd_polys[i] < 0' is always false.

```

https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/kernels/volk/volk_16i_max_star_horizontal_16i.h#L131
Can we change it to if(intermediate) or even if((num_bytes >> 4) & 1) And there is a crazy amount of those:
```
./volk/kernels/volk/volk_32fc_x2_conjugate_dot_prod_32fc.h	95	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_conjugate_dot_prod_32fc.h	421	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_dot_prod_32fc.h	96	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_dot_prod_32fc.h	531	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_16ic_convert_32fc.h	118	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_16ic_convert_32fc.h	251	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_16i_branch_4_state_8.h	101	note	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_16i_max_star_horizontal_16i.h	131	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_16u.h	314	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_16u.h	342	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_32u.h	272	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_32u.h	300	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h	314	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h	332	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_square_dist_32f.h	235	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_square_dist_32f.h	252	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_8u_x4_conv_k7_r2_8u.h	591	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_s32fc_x2_rotator_32fc.h	302	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_s32fc_x2_rotator_32fc.h	407	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_16u.h	147	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_16u.h	172	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_16u.h	502	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_16u.h	527	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_32u.h	136	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_32u.h	160	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_32u.h	453	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_index_max_32u.h	477	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h	141	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h	161	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h	179	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h	427	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_square_dist_32f.h	132	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_square_dist_32f.h	151	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_square_dist_32f.h	167	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_32fc_x2_square_dist_32f.h	376	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
./volk/kernels/volk/volk_8u_x4_conv_k7_r2_8u.h	302	err	V1008 Consider inspecting the 'for' operator. No more than one iteration of the loop will be performed.
```
https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/kernels/volk/volk_32f_acos_32f.h#L175
Why do we need this line? The same on 374, and 
```
./volk/kernels/volk/volk_32f_asin_32f.h	171	note	V537 Consider reviewing the correctness of 'z' item's usage.
./volk/kernels/volk/volk_32f_asin_32f.h	363	note	V537 Consider reviewing the correctness of 'z' item's usage.
./volk/kernels/volk/volk_32f_atan_32f.h	169	note	V537 Consider reviewing the correctness of 'z' item's usage.
./volk/kernels/volk/volk_32f_atan_32f.h	358	note	V537 Consider reviewing the correctness of 'z' item's usage.
```

Do we need this https://github.com/gnuradio/volk/blob/001e60a7f33cdc5430892201af88a332b67f5872/kernels/volk/volk_32f_x2_pow_32f.h#L777 (Also lines 400, 548, 162, 280, 666.)

### PR DESCRIPTION
**Pull request by ValZapod**
Partially fix #327

### CODE REVIEW

**Comment by ValZapod** [comment]
There is a mistake somewhere in `kernels: change one iteration for's to if's` i tried to fix that, but alas. Interesting moments. Python3.8 breaks builds of bb/*, so ASAP fix it... Second, previous to that commit has a green mar

File: kernels/volk/volk_32fc_x2_square_dist_32f.h [hunk 1]
```diff
@@ -392,7 +388,7 @@ volk_32fc_x2_square_dist_32f_u_avx2(float* target, lv_32fc_t* src0, lv_32fc_t* p
     target += 4;
   }
 
-  for(i = 0; i < leftovers1; ++i) {
+  if (num_bytes >> 3 & 0b11) {
```
Comment (jdemel) [inline kernels/volk/volk_32fc_x2_square_dist_32f.h]: That's probably the line that breaks the CI. `0b11` may result in `leftovers1 == 3`. Without the loop, Only the first of those 3 samples is processed. And the test complains that the last 2 samples are `0` instead of the correct value.

Comment (ValZapod) [reply kernels/volk/volk_32fc_x2_square_dist_32f.h]: You were right))

File: kernels/volk/volk_16i_branch_4_state_8.h [hunk 2]
```diff
@@ -98,73 +94,71 @@ volk_16i_branch_4_state_8_a_ssse3(short* target, short* src0, char** permuters,
...
 
-    _mm_store_si128(&p_target[2], xmm8);
+  _mm_store_si128(&p_target[2], xmm8);
 
-    _mm_store_si128(&p_target[3], xmm10);
+  _mm_store_si128(&p_target[3], xmm10);
 
-    p_target += 3;
-  }
+  p_target += 3;
```
Comment (michaelld) [inline kernels/volk/volk_16i_branch_4_state_8.h]: this line can be removed too

File: kernels/volk/volk_16i_max_star_horizontal_16i.h [hunk 3]
```diff
@@ -128,7 +127,7 @@ volk_16i_max_star_horizontal_16i_a_ssse3(int16_t* target, int16_t* src0, unsigne
     p_target += 1;
   }
 
-  for(i = 0; i < intermediate; ++i) {
+  if (num_bytes >> 4 & 1) {
```
Comment (michaelld) [inline kernels/volk/volk_16i_max_star_horizontal_16i.h]: Please leave the line `  int intermediate = (num_bytes >> 4) & 1;` and then use `intermediate`. Make it clear the connection between all of these statements. My request here is purely because this setting is used multiple times. For those other changes where the setting is used just once, it makes sense to remove the main variable and just use the setting directly in the code.

File: kernels/volk/volk_16i_branch_4_state_8.h [hunk 4]
```diff
@@ -98,73 +94,71 @@ volk_16i_branch_4_state_8_a_ssse3(short* target, short* src0, char** permuters,
...
-    xmm8 = _mm_shuffle_epi8(xmm5, xmm8);
-    xmm10 = _mm_shuffle_epi8(xmm5, xmm10);
+  xmm5 = _mm_load_si128(p_src0);
+  xmm0 = _mm_shuffle_epi8(xmm5, xmm0);
+  xmm6 = _mm_shuffle_epi8(xmm5, xmm6);
+  xmm8 = _mm_shuffle_epi8(xmm5, xmm8);
+  xmm10 = _mm_shuffle_epi8(xmm5, xmm10);
 
-    p_src0 += 4;
+  p_src0 += 4;
```
Comment (michaelld) [inline kernels/volk/volk_16i_branch_4_state_8.h]: this line can be removed too

File: kernels/volk/volk_16i_max_star_horizontal_16i.h (hunk 3 above)
Comment (ValZapod) [reply kernels/volk/volk_16i_max_star_horizontal_16i.h]: No, in this case code vs. memory. Use the variable if it is more two times.

File: kernels/volk/volk_16i_branch_4_state_8.h (hunk 4 above)
Comment (ValZapod) [reply kernels/volk/volk_16i_branch_4_state_8.h]: Yeah, it is just unused (!) I will also delete those then: 
`p_target = (__m128i*)target; 
  p_src0 = (__m128i*)src0;`

**Comment by ValZapod** [comment]
So I rebased on top of new master. I think we do need to add that variable, compiler will optimise, so out of 3 manipulations it will use only 2. Memory allocations and using it from and in it, on the other hand... I suppose most of kernel should be done in AVX/2 registers, right?

**Comment by jdemel** [comment]
I added the CLA label, since this is a rather large (more than 10 lines) change. In #327 @ValZapod you state you don't want to sign a CLA. @bhilburn how do we handle this PR?

**Comment by ValZapod** [comment]
@jdemel Hello! I signed CLA!

**Comment by michaelld** [comment]
> @jdemel Hello! I signed CLA with FSF! Back here [gnuradio/gnuradio#3079 (comment)](https://github.com/gnuradio/gnuradio/pull/3079#issuecomment-577902467)

Excellent! I've removed the CLA label. Let's review this, again if necessary & move forth with it!

**Comment by ValZapod** [comment]
@michaelld @hcab1 Looks like we just had https://github.com/gnuradio/volk/issues/254 
https://travis-ci.org/gnuradio/volk/builds/647859794?utm_source=github_status&utm_medium=notification Oops. 

Linux arm64 Clang qa_volk_32f_x3_sum_of_poly_32f  failed. 😎😎😎😎💩

**Comment by jdemel** [comment]
@ValZapod That's great news! Thanks for your contribution.

**Comment by jdemel** [comment]
> @michaelld @hcab14 Looks like we just had #254
> https://travis-ci.org/gnuradio/volk/builds/647859794?utm_source=github_status&utm_medium=notification Oops.
> 
> Linux arm64 Clang qa_volk_32f_x3_sum_of_poly_32f failed. 😎😎😎😎💩

CI passes now. So it should be fine. I just hope we don't see that error again. Otherwise we need to take action.

File: kernels/volk/volk_16i_max_star_horizontal_16i.h (hunk 3 above)
Comment (michaelld) [reply kernels/volk/volk_16i_max_star_horizontal_16i.h]: Yes, it is bitwise simple, but, again, it's used 3 times. What I mean here is to change this line from the `for` to your new `if`, but do `if(intermediate) {` ... ditto the 2 parts below. That way, one can look at the code and see `intermediate` and note how it is used in 3 places, rather than having to parse `(num_bytes >> 4 & 1)` 3 times to determine the connection.

File: kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h [hunk 5]
```diff
@@ -113,9 +113,7 @@ volk_32fc_x2_s32f_square_dist_scalar_mult_32f_a_avx2(float* target, lv_32fc_t* s
   __m256 xmm_points0, xmm_points1, xmm_result;
 
   const unsigned int bound = num_bytes >> 6;
-  const unsigned int leftovers0 = (num_bytes >> 5) & 1;
-  const unsigned int leftovers1 = (num_bytes >> 4) & 1;
-  const unsigned int leftovers2 = (num_bytes >> 3) & 1;
+  const unsigned int leftovers = (num_bytes >> 3) & 1;
```
Comment (michaelld) [inline kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h]: why not also get rid of this variable? ... looks like it's used just once ...

File: kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h [hunk 6]
```diff
@@ -342,9 +340,7 @@ volk_32fc_x2_s32f_square_dist_scalar_mult_32f_u_avx2(float* target, lv_32fc_t* s
...
```
Comment (michaelld) [inline kernels/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h]: ditto the prior comment about used just once ... or am I missing something?

File: lib/qa_utils.cc [hunk 7]
```diff
@@ -141,7 +141,7 @@ volk_type_t volk_type_from_string(std::string name) {
             type.is_signed = false;
             break;
         default:
-            throw;
+            throw "no such type!";
```
Comment (michaelld) [inline lib/qa_utils.cc]: I like this: let's feed back -something- useful! I'd like to augment this with the value of `name[i]` somehow: make it clear what the bad parsing type is; could be useful as feedback to the user as to what to look for to fix.

**Comment by ValZapod** [comment]
@michaelld We have a bigger problem. kernels: get rid of some assignments caused qa_volk_32f_x3_sum_of_poly_32f failures. Twice already.
https://travis-ci.org/gnuradio/volk/builds/647859794?utm_source=github_status&utm_medium=notification

https://travis-ci.org/gnuradio/volk/builds/648309957?utm_source=github_status&utm_medium=notification

**Comment by michaelld** [comment]
> @michaelld We have a bigger problem. kernels: get rid of some assignments caused qa_volk_32f_x3_sum_of_poly_32f failures. Twice already.
> https://travis-ci.org/gnuradio/volk/builds/647859794?utm_source=github_status&utm_medium=notification
> 
> https://travis-ci.org/gnuradio/volk/builds/648309957?utm_source=github_status&utm_medium=notification

Yes, but not for all builds ... which is interesting / odd. I'm looking into it.

**Comment by michaelld** [comment]
Those failures have nothing to do with this PR ... so let's keep working toward getting this one fixed up & merged ... then we'll work on the `qa_volk_32f_x3_sum_of_poly_32f` failures.

**Comment by michaelld** [comment]
> Those failures have nothing to do with this PR ... so let's keep working toward getting this one fixed up & merged ... then we'll work on the `qa_volk_32f_x3_sum_of_poly_32f` failures.

Oh ... so you're saying that the commit in this PR that tweaks the `acos` and such is creating this failure?

**Comment by ValZapod** [comment]
> Those failures have nothing to do with this PR ...

Dod you check other pull requests? Because if it has nothing to do then https://github.com/gnuradio/volk/issues/254 is jot fixed. But! There only NEON, i.e. arm64 is a problem, here amd64 also a problem.

> commit in this PR that tweaks the acos and such is creating this failure

Yes.

File: kernels/volk/volk_16i_max_star_horizontal_16i.h (hunk 3 above)
Comment (ValZapod) [reply kernels/volk/volk_16i_max_star_horizontal_16i.h]: I think we do not need to add that variable, compiler will optimise, so out of 3 manipulations it will use only 2. Memory allocations and using it from and in it, on the other hand... I suppose most of kernel should be done in AVX/2 registers, right?

Comment (michaelld) [reply kernels/volk/volk_16i_max_star_horizontal_16i.h]: My ask here is to help keep the code as readable and interpretable as one reasonably can. Keeping those 3 uses under the same variable might or not be faster that using the setting directly; I don't know & am not going to go testing it. That said, keeping those 3 uses under the same variable definitely helps keep the code as readable and interpretable. Hence my request to revert just that 1 variable's changes.

Comment (ValZapod) [reply kernels/volk/volk_16i_max_star_horizontal_16i.h]: Okay, will try to fix all of those.

File: kernels/volk/volk_16i_max_star_horizontal_16i.h [hunk 8]
```diff
@@ -148,7 +148,7 @@ volk_16i_max_star_horizontal_16i_a_ssse3(int16_t* target, int16_t* src0, unsigne
     p_target = (__m128i*)((int8_t*)p_target + 8);
   }
 
-  for(i = (bound << 4) + (intermediate << 3); i < (bound << 4) + (intermediate << 3) + leftovers ; i += 2) {
+  for(i = (bound << 4) + ((num_bytes >> 4 & 1) << 3); i < (bound << 4) + ((num_bytes >> 4 & 1) << 3) + leftovers ; i += 2) {
```
Comment (michaelld) [inline kernels/volk/volk_16i_max_star_horizontal_16i.h]: please revert the changes on this line, back to `intermediate`

File: lib/qa_utils.cc (hunk 7 above)
Comment (michaelld) [reply lib/qa_utils.cc]: this still

**Comment by ValZapod** [comment]
That commit is still a problem.

**Comment by jdemel** [comment]
@ValZapod thanks for working on this PR. 
Did GitHub just duplicate parts of this review? It seems like that happened. Maybe this is related to a `force-push`. Just a wild guess.

**Comment by michaelld** [comment]
The CI that's working looks good for this change.

File: kernels/volk/volk_16i_branch_4_state_8.h [hunk 9]
```diff
@@ -98,73 +94,67 @@ volk_16i_branch_4_state_8_a_ssse3(short* target, short* src0, char** permuters,
...
-    xmm6 = _mm_shuffle_epi8(xmm5, xmm6);
-    xmm8 = _mm_shuffle_epi8(xmm5, xmm8);
-    xmm10 = _mm_shuffle_epi8(xmm5, xmm10);
+  xmm5 = _mm_load_si128(p_src0);
+  xmm0 = _mm_shuffle_epi8(xmm5, xmm0);
+  xmm6 = _mm_shuffle_epi8(xmm5, xmm6);
+  xmm8 = _mm_shuffle_epi8(xmm5, xmm8);
+  xmm10 = _mm_shuffle_epi8(xmm5, xmm10);
 
-    p_src0 += 4;
```
Comment (jdemel) [inline kernels/volk/volk_16i_branch_4_state_8.h:108]: Why did you remove this line? Shouldn't the source vector be moved in every iteration?

Also `ctest -V -R branch_4` revealed:
```
2: Did not run a test for kernel: volk_16i_branch_4_state_8 !
1/1 Test #2: qa_volk_16i_branch_4_state_8 .....   Passed    0.00 sec
```
In other words we do not have a test for this kernel which is a problem. Also, this makes it more difficult to verify if the changes here are correct.

Comment (michaelld) [reply kernels/volk/volk_16i_branch_4_state_8.h:108]: `p_src0` is no longer used after the line above `xmm5 = _mm_load_si128(p_src0);` ... so it's wasteful to manipulate it here.

Comment (michaelld) [reply kernels/volk/volk_16i_branch_4_state_8.h:108]: Grrr... about not having a test for this!

Comment (jdemel) [reply kernels/volk/volk_16i_branch_4_state_8.h:108]: I see, the loop was removed entirely. Yeah, in that case, this line can go.

Comment (ValZapod) [reply kernels/volk/volk_16i_branch_4_state_8.h]: I will still rebase it.

**Comment by ValZapod** [comment]
@michaelld Can you help me with how to throw a variable value (and in this array[i] in for loop), I am not familiar with catch throw thing.

**Comment by michaelld** [comment]
> @michaelld Can you help me with how to throw a variable value (and in this array[i] in for loop), I am not familiar with catch throw thing.

Do you mean the `throw` you changed at `lib/qa_utils.cc:144`? Or the general C++ "how to catch a throw" methodology? This page is very good at describing how to do the general C++ try/catch < https://en.cppreference.com/w/cpp/language/try_catch >; see also < https://en.cppreference.com/w/cpp/language/throw >. If not those, please provide a little more detail as to what you're referring to.

**Comment by ValZapod** [comment]
> Do you mean the throw you changed at lib/qa_utils.cc:144

Yeah, that one without the catch.

File: lib/qa_utils.cc (hunk 7 above)
Comment (ValZapod) [reply lib/qa_utils.cc]: This one.

**Comment by michaelld** [comment]
> > Do you mean the throw you changed at lib/qa_utils.cc:144
> 
> Yeah, that one without the catch.

Is your question with regard to what I was asking for originally? I'm really not following yet.

File: lib/qa_utils.cc (hunk 7 above)
Comment (ValZapod) [reply lib/qa_utils.cc]: https://stackoverflow.com/questions/12261915/how-to-throw-stdexceptions-with-variable-messages How do you throw a variable name[i]?

Comment (michaelld) [reply lib/qa_utils.cc]: gotcha. let me figure that one out & get back shortly ...

Comment (michaelld) [reply lib/qa_utils.cc]:
```
throw std::runtime_error (std::string ("Error: no such type: '") + name[i] + "'");
```

Comment (ValZapod) [reply lib/qa_utils.cc]: > throw std::runtime_error("check(): Hidden node count of " + std::to_string(N_size_file) + " exceeds maximum allowed value of " + std::to_string(_N_MAX));

So, something like that. Found here: http://www.cplusplus.com/forum/beginner/57892/#msg311957
Is it safe? Or not? And can you do std::to_string in a loop??

Comment (michaelld) [reply lib/qa_utils.cc]: In our specific case here, `name[i]` is a `char`, and `std::string::operator+` covers the case of `std::string + char` ... so nothing special required in this specific case. If the argument were not a `char` then we'd have to do something else like `std::to_string`.

Comment (ValZapod) [reply lib/qa_utils.cc]: Okay, thanks. Hope we will merge this in 30 minutes ;)

**Comment by ValZapod** [comment]
@michaelld That is all. I can rebase qa_utils to one commit of you want.

**Comment by michaelld** [comment]
> @michaelld That is all. I can rebase qa_utils to one commit of you want.

I think it's OK as 3 commits, since each does something different.

**Comment by michaelld** [comment]
@jdemel what do you think?

**Comment by michaelld** [comment]
Relevant CI passes. 2 approvals. CLA in place. Small changes that are relevant. Merging.
