### PR TITLE
Ranking: Fail in a sensible manner, print useful info

### LINKED ISSUE #516: volk_get_index broken, stuck in infinite loop
While debugging gnuradio/gnuradio#5013, I stumbled across `volk_get_index` calling itself indefinitely when using `volk_8u_x2_encodeframepolar_8u` (at least on Deb11). No matter the reason for finding the right implementation of that kernel failing, this function mustn't go into infinite recursion.

Maybe, we should just actually `return -1;` and deal with that (by `abort`ing) in the calling functions `volk_rank_archs` and `volk.tmpl.c`: `${kern.name}_manual`. That would at least make debugging easier.

```
(gdb) bt
#0  volk_get_index (impl_name=<optimized out>, n_impls=<optimized out>, impl_names=<optimized out>) at ./lib/volk_rank_archs.c:44
#1  volk_rank_archs (kern_name=kern_name@entry=0x7fd65caaf788 "volk_8u_x2_encodeframepolar_8u", impl_names=impl_names@entry=0x7fd65cb8da90 <volk_machine_avx2_64_mmx_orc+67632>, impl_deps=impl_deps@entry=0x7fd65cb8db50 <volk_machine_avx2_64_mmx_orc+67824>,
    alignment=alignment@entry=0x7fd65cb8dbb0 <volk_machine_avx2_64_mmx_orc+67920>, n_impls=n_impls@entry=4, align=align@entry=true) at ./lib/volk_rank_archs.c:68
#2  0x00007fd65c986088 in __init_volk_8u_x2_encodeframepolar_8u () at ./obj-x86_64-linux-gnu/lib/volk.c:10997
#3  __volk_8u_x2_encodeframepolar_8u (frame=0x10d7a80 "", temp=0x12c1da0 "", frame_size=16) at ./obj-x86_64-linux-gnu/lib/volk.c:11022
#4  0x00007fd65b998230 in gr::fec::code::polar_decoder_sc_systematic::generic_work(void*, void*) () from /gnuradio/build/gr-fec/lib/libgnuradio-fec.so.3.10.0git
#5  0x00007fd65b95a37f in gr::fec::decoder_impl::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) () from /gnuradio/build/gr-fec/lib/libgnuradio-fec.so.3.10.0git
#6  0x00007fd65cf2de7a in gr::block_executor::run_one_iteration() () from /gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime.so.3.10.0git
#7  0x00007fd65cfa159a in gr::tpb_thread_body::tpb_thread_body(std::shared_ptr<gr::block>, std::shared_ptr<boost::barrier>, int) () from /gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime.so.3.10.0git
#8  0x00007fd65cf92b44 in gr::thread::thread_body_wrapper<gr::tpb_container>::operator()() () from /gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime.so.3.10.0git
#9  0x00007fd65d1bf787 in boost::(anonymous namespace)::thread_proxy (param=<optimized out>) at libs/thread/src/pthread/thread.cpp:179
#10 0x00007fd65f0c3ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007fd65ee56def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) n

Thread 3 "fec_decoder4" hit Breakpoint 2, volk_get_index (impl_name=<optimized out>, n_impls=<optimized out>, impl_names=<optimized out>) at ./lib/volk_rank_archs.c:36
36	in ./lib/volk_rank_archs.c
(gdb) bt
#0  volk_get_index (impl_name=<optimized out>, n_impls=<optimized out>, impl_names=<optimized out>) at ./lib/volk_rank_archs.c:36
#1  volk_rank_archs (kern_name=kern_name@entry=0x7fd65caaf788 "volk_8u_x2_encodeframepolar_8u", impl_names=impl_names@entry=0x7fd65cb8da90 <volk_machine_avx2_64_mmx_orc+67632>, impl_deps=impl_deps@entry=0x7fd65cb8db50 <volk_machine_avx2_64_mmx_orc+67824>,
    alignment=alignment@entry=0x7fd65cb8dbb0 <volk_machine_avx2_64_mmx_orc+67920>, n_impls=n_impls@entry=4, align=align@entry=true) at ./lib/volk_rank_archs.c:68
#2  0x00007fd65c986088 in __init_volk_8u_x2_encodeframepolar_8u () at ./obj-x86_64-linux-gnu/lib/volk.c:10997
#3  __volk_8u_x2_encodeframepolar_8u (frame=0x10d7a80 "", temp=0x12c1da0 "", frame_size=16) at ./obj-x86_64-linux-gnu/lib/volk.c:11022
#4  0x00007fd65b998230 in gr::fec::code::polar_decoder_sc_systematic::generic_work(void*, void*) () from /gnuradio/build/gr-fec/lib/libgnuradio-fec.so.3.10.0git
#5  0x00007fd65b95a37f in gr::fec::decoder_impl::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) () from /gnuradio/build/gr-fec/lib/libgnuradio-fec.so.3.10.0git
#6  0x00007fd65cf2de7a in gr::block_executor::run_one_iteration() () from /gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime.so.3.10.0git
#7  0x00007fd65cfa159a in gr::tpb_thread_body::tpb_thread_body(std::shared_ptr<gr::block>, std::shared_ptr<boost::barrier>, int) () from /gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime.so.3.10.0git
#8  0x00007fd65cf92b44 in gr::thread::thread_body_wrapper<gr::tpb_container>::operator()() () from /gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime.so.3.10.0git
#9  0x00007fd65d1bf787 in boost::(anonymous namespace)::thread_proxy (param=<optimized out>) at libs/thread/src/pthread/thread.cpp:179
#10 0x00007fd65f0c3ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007fd65ee56def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

This is a tail recursion in `volk_get_index`. Sadly, it will never terminate (until it causes memory exhaustion in ctest, I guess). 

`volk_get_index` is a bag of mixed emotions for me:

```C
int volk_get_index(const char* impl_names[], // list of implementations by name
                   const size_t n_impls,     // number of implementations available
                   const char* impl_name     // the implementation name to find
)
{
    unsigned int i;
    for (i = 0; i < n_impls; i++) {
        if (!strncmp(impl_names[i], impl_name, 20)) {
            return i;
        }
    }
    // TODO return -1;
    // something terrible should happen here
    fprintf(stderr, "Volk warning: no arch found, returning generic impl\n");
    return volk_get_index(impl_names, n_impls, "generic"); // but we'll fake it for now
}
```

1. `strncmp(a,b,20)`: We'll happily compare equal impls that are only different after the first 20 characters.
2. It never checks whether the impl that can't be found *is* the `_generic` one. If that is the case, it just recurses to looking up the generic one, and we end up where we are.

What *is* confusing is why neither `volk_get_info` nor the `volk_profile` tool *know* of `volk_8u_x2_encodeframepolar_8u_generic`. In fact, the latter doesn't seem to want to know any implementations of that at all.

_Originally posted by @marcusmueller in https://github.com/gnuradio/gnuradio/issues/5013#issuecomment-923369047_

### PR DESCRIPTION
**Pull request by marcusmueller**
Closes #516

### CODE REVIEW

File: lib/volk_rank_archs.c [hunk 1]
```diff
@@ -21,14 +21,36 @@ int volk_get_index(const char* impl_names[], // list of implementations by name
...
     // TODO return -1;
     // something terrible should happen here
-    fprintf(stderr, "Volk warning: no arch found, returning generic impl\n");
+    if (!strcmp("generic", impl_name)) {
+        // we're in the error case, and we've already tried to look for the generic
+        // implementation, and failed: There's no good way to proceed here.
+        fprintf(stderr,
+                "Volk warning: tried to find \"generic\" impl, but failed. "
+                "Returning index 0, just to give any working implementation.\n");
+        return 0;
```
Comment (jdemel) [inline lib/volk_rank_archs.c:49]: Looking at the previous `return -1` for errors, wouldn't you want the same value here too? Also, since `-1` is an error condition, a quick `#define ERROR_IMPL_NOT_FOUND -1` would probably help long term =D

**Review by jdemel — COMMENTED** [review]
Thanks! One little comment but besides: LGTM.

File: lib/volk_rank_archs.c (hunk 1 above)
Comment (marcusmueller) [reply lib/volk_rank_archs.c:49]: no, I don't want that. (We've never returned -1 before, the case where n_impls == 0 is something where there's absolutely no way to continue. So far we've just been happily falling back to things. If we break that behaviour, and I agree we absolutely should, then we need to mark this as a relevant API break including versioning and everything. So far, this can all end up in a patch release.)

**Comment by marcusmueller** [comment]
@jdemel  I think we should more broadly have a design roundtable on how we'd like our dispatching API to look like. I'm tempted to think we should probably should think about our endless kernel .h files, our repetitive and historically very bugprone "and now we also deal with the final n_points%(SIMD multiple) values", and make use of the fact that we could, in fact, let kernels return the number of items processed.

This might call for a mightier interface than our current "the symbol you're using is bent towards the generally optimal implementation at ldload time".

File: lib/volk_rank_archs.c (hunk 1 above)
Comment (jdemel) [reply lib/volk_rank_archs.c:49]: The previous behavior would be: Find the correct impl and return the index, that's preserved. But now, the error handling changes:
1. If there's no impl -> return -1, which is a good improvement.
2. return 0, for whatever impl if we couldn't find one and we weren't looking for the generic impl.
3. recursive call to `volk_get_index` with `"generic"` is never reached anymore. Either, we returned the correct index for generic already, or we returned 0, or we are back to the infinite loop case that the PR is trying to fix.

unless I just misunderstood the code, it looks like this would need some more attention.

File: tmpl/volk.tmpl.c [hunk 2]
```diff
@@ -136,8 +136,17 @@ static inline void __init_${kern.name}(void)
...
+
+    // find the highest-ranked implementation for a given kernel. Will
+    // (warningly) fall back to "generic" if the specified name couldn't be found,
+    // and will properly fail with -1 if there's no implementations at all.
+    const int index_a = volk_rank_archs(
+        name, impl_names, impl_deps, alignment, n_impls, true /*aligned*/);
+    const int index_u = volk_rank_archs(
+        name, impl_names, impl_deps, alignment, n_impls, false /*unaligned*/);
+    assert(index_a >= 0);
+    assert(index_u >= 0);
```
Comment (jdemel) [inline tmpl/volk.tmpl.c:148]: Assert should not be present in a release compile anymore. Is this check still intentional?

**Comment by jdemel** [comment]
These are all very valid points. I'd really like to improve in every area. My understanding of your suggestions is that we'd design VOLK v4 though because this is a major API breaking change. We can discuss this but I argue that the comments to a PR might not be the right place.

> @jdemel I think we should more broadly have a design roundtable on how we'd like our dispatching API to look like. I'm tempted to think we should probably should think about our endless kernel .h files, our repetitive and historically very bugprone "and now we also deal with the final n_points%(SIMD multiple) values", and make use of the fact that we could, in fact, let kernels return the number of items processed.

So these are multiple bullets:
- "endless kernel header files", would you like to have headers for every implementation? The current library design wouldn't allow for compilation units here.
- tail handling: yes improvements would be great. If we start to discuss this, we might want to rephrase this to prologue/epilogue handling though.
- Return number of processed samples: This would be a very different API, at least potentially.

> This might call for a mightier interface than our current "the symbol you're using is bent towards the generally optimal implementation at ldload time".

I would assume you don't want to re-check the implementation again and again during runtime. I would expect that VOLK continues to run on the same CPU (or at the very least the same kind of CPU if you really migrate between servers) but migrating to an entirely different CPU would also imply a re-launch of the application and then, we can re-load the optimal implementations.

File: lib/volk_rank_archs.c (hunk 1 above)
Comment (marcusmueller) [reply lib/volk_rank_archs.c:49]: no, it's

1. if no impl => -1
2. if desired impl not found, return index of "generic"
3. if "generic" isn't found, but was asked for, return 0


The 1-depth recursion to find "generic" in case 2. still exists

File: tmpl/volk.tmpl.c (hunk 2 above)
Comment (marcusmueller) [reply tmpl/volk.tmpl.c:148]: it's an intentional check in conformance with the two asserts four lines down from there ;) 

But I'd agree, we *should* be doing better. Any recommendations?

Comment (jdemel) [reply tmpl/volk.tmpl.c:148]: I see, it was just past the review window =D

**Review by jdemel — APPROVED** [review]
LGTM. The discussion raised some general concerns that require further considerations. They're out of scope for this PR. Thanks :)
